language: node_js

node_js:
  - 6
  - 7

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
notifications:
  slack:
    secure: ONjyR0uwGzt+0JcrZjqKMrWHIeHuDpUwxXYM10WYZzLcPf26zIweA8g18G+rMisvBKk501IeVtkIzxKjUFjBIvQeqN0aBJ4NuKjvrYgf9YVFYk4tRGn+zrPle3IWoIt+cFy5WAsiDx6VXLKmPbGQP1I059S3Rtqpu2WRDgx00fCHZMsIxgZ5k6/GFmyzvLnULoCuu1Cr/Ul6WGz7lpOG4SiN80n4R44J2Hgn7dOHcPnBLwY/kEnJWXhk/vPb0ikFW+w2T/anBbKmfGtMODH0h0WRbAqKQAB/YuwuNZMZpaWZRkQEPMKI/eTk+/p3UQLtMBx29tnih+9Gxz9qxCPE1cMQf6C2IWfnTcWsqjhXKF3jS7jGUqit+6lZH+8DEP4TlgXihSw70GA+SXVcODCbqxuAq0UyqDK0gzlONQuDvY7k1/DEp5VzKCSAfy8y6B5zduyYhwLJy8DyEgaih/1Y7dsENFCu//LUzhSNyis/lBEpx4LlgUlggYOf/Brm02Zzd7fXewGHmAaazUo6rS7JBEOnFDqu44Y92chi95/I7lYqtMXulibssAOYgHnPK0MXAmwLxFMphZk1VD5GvWN80fG1bbSGw6++003TO00mH3HFgSG9/xMltt9qj01l1xJa+ihYFtELijiGUBJkVWCdYbyrteaFWuNAP14lgR2x3Po=
