language: node_js

node_js:
  - 7
  - 6
  - 4

matrix:
  fast_finish: true

env:
  - CXX=g++-4.8

before_install:
  - npm -g install npm@latest
  - node --version
  - npm --version

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
